name: 'gameday_analytics'
version: '1.0.0'
config-version: 2

profile: 'gameday_analytics'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gameday_analytics:
    staging:
      +materialized: view
      # +schema: staging  # For Postgres/Snowflake/BigQuery - creates separate schema namespaces
    intermediate:
      +materialized: view
      # +schema: intermediate  # SQLite limitation: all objects in 'main' schema with prefixed names
    marts:
      +materialized: table
      # +schema: marts  # Production warehouses use this to organize: staging.*, intermediate.*, marts.*